version: "3.8"
services:

  # Database Postgres
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=school_project
      - POSTGRES_USER=dbadmin
      - POSTGRES_PASSWORD=abc123!
    container_name: postgres_db

  # Django Application
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    image: app:schoolproject
    container_name: django_school_project
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db




