# Generated by Django 4.1.5 on 2023-01-15 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Exam Type', max_length=255, verbose_name='Exam Title')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exam Tyoe',
                'verbose_name_plural': 'Exam Type',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UploadQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_description', models.TextField()),
                ('exam_folder', models.FileField(help_text='Upload Zip Folder of files', upload_to='exams', verbose_name='Exam Folder')),
                ('total_marks', models.PositiveIntegerField()),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.examtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.uploadquiz')),
                ('submit_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
