# Generated by Django 4.1.5 on 2023-01-21 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_uploadquiz_total_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examtype',
            options={'ordering': ['id'], 'verbose_name': 'Exam Type', 'verbose_name_plural': 'Exam Type'},
        ),
        migrations.AddField(
            model_name='examtype',
            name='image_type',
            field=models.ImageField(null=True, upload_to='exam_type'),
        ),
        migrations.AlterField(
            model_name='uploadquiz',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_type_quiz', to='core.examtype'),
        ),
    ]
