# Generated by Django 4.1.5 on 2023-01-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_examtype_options_examtype_image_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='submit_files',
            field=models.FileField(default=1, upload_to='submitFiles'),
            preserve_default=False,
        ),
    ]
