# Generated by Django 4.1.5 on 2023-01-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_examresult_submit_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='grade',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
