# Generated by Django 4.1.5 on 2023-01-22 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_examresult_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_result', to='core.uploadquiz'),
        ),
    ]
